# Generated by Django 5.2.13 on 2026-06-14 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DelegateRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('school', models.CharField(max_length=200)),
                ('grade', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=20)),
                ('experience', models.CharField(choices=[('novice', 'Novice'), ('experienced', 'Experienced'), ('veteran', 'Veteran')], max_length=20)),
                ('committee_1', models.CharField(max_length=60)),
                ('committee_2', models.CharField(max_length=60)),
                ('transaction_id', models.CharField(max_length=120)),
                ('dietary', models.TextField(blank=True, default='')),
                ('confirmed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
